### ISSUE TITLE
Support for local RequirementDefinition for the terraformProvider property

### ISSUE THREAD

**Issue by rraziel** [hashicorp/cdktf-provider-project#215]
Hello,

Right now, the `terraformProvider` property passed to `CdktfProviderProject` can only be a `string` (cf. [here](https://github.com/hashicorp/cdktf-provider-project/blob/main/src/index.ts#L38)).

However, the `cdktf.json` file also allows providers to be a `RequirementDefinition` with a `name`, a `source` and a `version`.

It would be nice to be able to use the same object with `CdktfProviderProject`, not only to align it with `cdktf.json` but also because it opens the door to having the Provider and the codegen for Java/TS/etc. in the same repository.

If that's considered useful, I can create a PR for it.

**Comment by jsteinich** [comment]
There's actually a different type used internally to cdktf. See https://github.com/hashicorp/terraform-cdk/blob/3cf9fccfb10ce9370857e0931ade838beb35cd6a/packages/%40cdktf/provider-generator/lib/config.ts#L193.



> but also because it opens the door to having the Provider and the codegen for Java/TS/etc. in the same repository.

I'm not sure I'm following this. The provider generation already creates packages for each language.

**Comment by rraziel** [comment]
Well maybe it's something that can be done while passing a string, but is there a way to create the (Java/TS/etc.) packages without publishing the Terraform provider to the registry first?

i.e. pass a path to a local directory where the package has been built.

Or do you have to basically have for example a GH action that publishes the Terraform provider to the registry, then in a second step reference that published package to generate language-specific packages?

**Comment by jsteinich** [comment]
> is there a way to create the (Java/TS/etc.) packages without publishing the Terraform provider to the registry first?

Yes. Take a look at https://www.terraform.io/cdktf/concepts/providers-and-resources#use-a-local-provider

**Comment by rraziel** [comment]
Ah great thanks, then I suppose there's not much need for this issue to exist, I will close it (great work being done on the CDK and Terraform in general btw).
